config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    
    if @comment.save
      redirect_to @post
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order("created_at DESC")
  end
  
  def show
    @comments = @post.comments
  end
  
  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  def upvote
    @post.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end
  
  def downvote
    @post.downvote_by current_user
    redirect_back(fallback_location: root_path)
  end
  
  private
    
    def find_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :link, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :content, label: "Reply to thred"
  = f.button :submit, class: "button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribbble</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = image_tag @post.image.url(:small) if @post.image_file_name.present?
  = f.input :image
  = f.input :title
  = f.input :link
  = f.input :description
  
  =f.button :submit

app/views/posts/edit.html.haml
%h1 Edit your inspiration

= render 'form'
= link_to 'Cancel', @post

app/views/posts/index.html.haml
- @posts.each do |post|
  = link_to (image_tag post.image.url(:small)), post if post.image_file_name.present?
  %h2= link_to post.title, post
  %p
    = pluralize(post.comments.count, "Comment")
  %p
    = post.get_likes.size
    Likes
  
= link_to "Add new inpiration", new_post_path

app/views/posts/new.html.haml
%h1 add new inpiration

= render 'form'

app/views/posts/show.html.haml
= image_tag @post.image.url(:medium) if @post.image_file_name.present?
%h1= @post.title
%p= @post.link
%p= @post.description
%p= @post.user.name
%p
  = @post.get_upvotes.size
  Likes
%p
  = @post.get_downvotes.size
  Dislikes
= link_to "Like", like_post_path(@post), method: :get
= link_to "Dislike", dislike_post_path(@post), method: :get

#comment
  %h2.comment_count= pluralize(@post.comments.count, "Comment")
  - @comments.each do |comment|
    .comment
      %p.username= comment.user.name
      %p.content= comment.content
  = render 'comments/form'
- if @post.user == current_user
  = link_to "Edit", edit_post_path(@post)
= link_to "Delete", post_path(@post), method: :delete, dat: {confirm: "Are you sure?"}
= link_to "Home", root_path